config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  get 'posts/new' => 'posts#new'
  post 'posts'    => 'posts#create'
  delete 'posts/:id'=> 'posts#destroy'
  patch   'posts/:id'  => 'posts#update'
  get   'posts/:id/edit'  => 'posts#edit'
  resources :users, only: [:edit, :update, :show, :destroy] do
    get 'battle' => 'users#battle'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user).page(params[:page]).per(9).order("created_at DESC")
  end

  def new
    @posts = Post.new
  end

  def create
    Post.create(title: post_params[:title], text: post_params[:text], user_id: current_user.id)
    redirect_to root_path
  end

  def destroy
    post = Post.find(params[:id])
    if post.user_id == current_user.id
      post.destroy
    end
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.user_id == current_user.id
      post.update(post_params)
    end
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def show
    @users = User.all
    @name = current_user.name
    @level = current_user.level
    @hp = current_user.hp
    @attack = current_user.attack
    @posts = current_user.posts.page(params[:page]).per(5).order("created_at DESC")
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def battle
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.html
      format.json 
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
  - if notice.present?
    .alert.alert-dismissable.alert-success
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      %p= notice
  - if alert.present?
    .alert.alert-dismissable.alert-danger
      %button.close{"data-dismiss" => "alert", :type => "button"} ×
      %p= alert

app/views/posts/_post.html.haml
-@posts.each do |post|
  .card
    .card-block.border-dark
      .card-header.text-dark
        ="#{post.user.name} さん"
        .n
        =post.title
      .card-body.text-muted
        =post.text
      - if user_signed_in? && current_user.id == post.user_id
        %button.btn.bg-secondary
          = link_to 'edit', "/posts/#{post.id}/edit", method: :get
        %button.btn.bg-secondary
          = link_to 'delete', "/posts/#{post.id}", method: :delete

app/views/posts/edit.html.haml
%html{:lang => "ja"}
  %head
  %body.bg-light
%link#bootstrap-css{:href => "//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css", :rel => "stylesheet"}/
%script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"}
%script{:src => "//code.jquery.com/jquery-1.11.1.min.js"}
/ ---- Include the above in your HEAD tag --------
%link{:href => "http://fonts.googleapis.com/css?family=Raleway:400,200", :rel => "stylesheet", :type => "text/css"}/
.container
  .row.login_box
    .col-md-12.col-xs-12{:align => "center"}
      %h3 Edit post
    .col-md-12.col-xs-12.login_control
      = form_for @post, url: "/posts/#{@post.id}", method: :patch do |f|
        .control
          .label Title
          = f.text_field :title ,class: 'form-control bg-secondary',class:"form-control"
        .control
          .label Text
          = f.text_area :text ,class: 'form-control bg-secondary',class:"form-control"
        %div{:align => "center"}
          = f.submit "Repost", class: 'btn btn-orange'
  %footer.text-light
    .container
      %p.float-right

app/views/posts/index.html.haml
!!!
%html{:lang => "ja"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %link{:href => "/docs/4.0/assets/img/favicons/favicon.ico", :rel => "icon"}/
    %title Album example for Bootstrap
    %link{:href => "https://getbootstrap.com/docs/4.0/examples/album/", :rel => "canonical"}/
    / Bootstrap core CSS
    %link{:href => "../../dist/css/bootstrap.min.css", :rel => "stylesheet"}/
    / Custom styles for this template
    %link{:href => "album.css", :rel => "stylesheet"}/
    / Bootstrap4
    %script{:crossorigin => "anonymous", :integrity => "sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"}
    /Masonry
    %script{:src => "https://unpkg.com/masonry-layout@4.2.1/dist/masonry.pkgd.min.js"}
  %body.bg-light
    %header
      .navbar.navbar-dark.bg-dark.box-shadow
        .container.d-flex.justify-content-between
          %a.navbar-brand.d-flex.align-items-center{:href => "#"}
            %svg.mr-2{:fill => "none", :height => "20", :stroke => "currentColor", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2", :viewbox => "0 0 24 24", :width => "20", :xmlns => "http://www.w3.org/2000/svg"}
              = image_tag 'dog.png', size: "50x50", alt: "test"
            %strong TEST BLOG
          %button.navbar-toggler{"aria-controls" => "navbarHeader", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarHeader", "data-toggle" => "collapse", :type => "button"}
            %span.navbar-toggler-icon
      #navbarHeader.collapse.bg-dark
        .container
          .row
            %ul.list-unstyled
              - if user_signed_in?
                %li
                  = link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn'
                %li
                  = link_to "Post", posts_new_path, method: :get, class: 'btn'
                %li
                  = link_to "たたかう", "/users/#{current_user.id}", method: :get, class: 'btn retro'
              - else
                %li
                  = link_to "Log in", new_user_session_path, method: :get, class: 'btn'
                %li
                  = link_to "Registeration", new_user_registration_path, method: :get, class: 'btn'
    %main{:role => "main"}
      %section
      .container
        .card-columns.pt-5
          =render partial: "post"
      = paginate @posts
    %footer.text-light
      .container
        %p.float-right
          %a.text-light{:href => "#"} move to top
        %p using example from © Bootstrap
    /
      Bootstrap core JavaScript
      \==================================================
    / Placed at the end of the document so the pages load faster
    %script{:crossorigin => "anonymous", :integrity => "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN", :src => "https://code.jquery.com/jquery-3.2.1.slim.min.js"}
    :javascript
      window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')
    %script{:src => "../../assets/js/vendor/popper.min.js"}
    %script{:src => "../../dist/js/bootstrap.min.js"}
    %script{:src => "../../assets/js/vendor/holder.min.js"}

app/views/posts/new.html.haml
%link#bootstrap-css{:href => "//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css", :rel => "stylesheet"}/
%script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"}
%script{:src => "//code.jquery.com/jquery-1.11.1.min.js"}
/ ---- Include the above in your HEAD tag --------
%link{:href => "http://fonts.googleapis.com/css?family=Raleway:400,200", :rel => "stylesheet", :type => "text/css"}/
.container
  .row.login_box
    .col-md-12.col-xs-12{:align => "center"}
      %h3 Post new
    .col-md-12.col-xs-12.login_control
      = form_for (@posts) do |f|
        .control
          .label Title
          = f.text_field :title ,class: 'form-control bg-secondary',class:"form-control"
        .control
          .label Text
          = f.text_area :text ,class: 'form-control bg-secondary',class:"form-control"
        %div{:align => "center"}
          = f.submit "Post", class: 'btn btn-orange'

app/views/users/battle.html.haml
.container.retro
  - hero = current_user.name
  - enemyhp = @user.hp
  - herohp = current_user.hp
  - enemy = @user.name 
  .blackboard.retro
    #point.retro
  .blackboard.retro
    #epoint.retro
  .blackboard.retro
    #result.retro
    .n
    #eresult.retro-yellow
    .n
    #plusresult.retro
  .blackboard.retro
    ="#{enemy} が あらわれた！"
    .n
    ="どうする？"
    .n
    %p.battlestart.retro.sentaku こうげき

app/views/users/show.html.haml
.contents
  %p.retro だれと？
  -@users.each do |user|
    - unless user == current_user
      .blackboard.retro
        = link_to user.name, "/users/#{user.id}/battle", method: :get, class: 'retro sentaku'